"""MOD: ProductGroup as tree with relations

Revision ID: 364ee536e08d
Revises: 9fa423b33445
Create Date: 2022-07-07 12:42:31.366948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '364ee536e08d'
down_revision = '9fa423b33445'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('parent_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_product_groups_group_id'), ['group_id'])
        batch_op.create_foreign_key(batch_op.f('fk_product_groups_parent_id_product_groups'), 'product_groups', ['parent_id'], ['group_id'])
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_product_groups_parent_id_product_groups'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_product_groups_group_id'), type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
