#: import get_color_from_hex kivy.utils.get_color_from_hex

<CRoot>
	MDBoxLayout:
		orientation: 'vertical'

		MDToolbar:
			height: 50
			elevation: 10
			title: 'CIN'

		MDBoxLayout:
			MDNavigationRail:
				elevation: 10

				MDNavigationRailItem:
					icon: 'point-of-sale'
					text: 'Sale'

				MDNavigationRailItem:
					icon: 'cog-outline'
					text: 'Settings'

			MDBoxLayout:
				padding: "24dp"

				ScrollView:

					MDList:
						id: box
						cols: 3
						spacing: "12dp"
